- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportConfiguration.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataValidationError.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataValidationRequest.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataValidationResult.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerDataValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/VirtoCommerce.CustomerExportImportModule.Core.csproj
- src/VirtoCommerce.CustomerExportImportModule.Data/Models/CsvCustomer.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerDataValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportHelper.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Content/css/customer-export-import.css
- src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.tpl.html
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/resources/resources.js
- src/VirtoCommerce.CustomerExportImportModule.Web/webpack.config.js
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-12-99285171.zip
> VDS-1374: Set limits of the file to upload

- .github/workflows/deploy-pr.yml
- .github/workflows/deploy.yml
Rewritten update deployment-cm step to use create-deploy-pr instead of
direct commit from PowerShell commit
> VDS-1269: Fix CLA error

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportDataRequest.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/ExportImportMemberSearchService.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
Description: 
--
QA-test:  VDS-1396
Demo-test: VDS-1398
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-19-4a405756.zip
> VDS-1798 Implement workaround for deep search customers into organization

- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
Description: 
--
QA-test: 
Demo-test: 
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-21-3ddcfa4f.zip
> VDS-1793 Write to end test to class msps

- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
Description: 
--
QA-test: VDS-1852
Demo-test: VDS-1853
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-23-5dd485f4.zip
> VDS-1851: Remove "s" in the word "Files" in Import/Export Contact blade.

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportValidationState.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerDataExporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerExportPagedDataSource.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntitiesAreNotDuplicatesValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntityAreNotDuplicatesValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntityIsNotDuplicateValidator.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerExportPagedDataSourceTests.cs
Description: 
--
QA-test: 
Demo-test: 
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-24-fc1c8500.zip
> VDS-1836: Add logic for duplicates validation

- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-25-3498d70d.zip
> VDS-1829: Fix bug with toolbar items visibility

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/ExportImport/GenericClassMap.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/ByFieldValuesEqualityComparer.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerExportPagedDataSourceTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/TestHelper.cs
Description: 
--
QA-test: VDS-1840
Demo-test: VDS-1841
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-26-b862b8da.zip
> VDS-1839: Make optional columns not required in header

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExtendedMemberSearchCiteria.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataRequest.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportPushNotification.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerImportReporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerImportReporterFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvPagedCustomerDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICustomerImportPagedDataSource.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ImportPushNotificationExtensions.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportReporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportReporterFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedCustomerDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPriceImportReporterFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerImportPagedDataSource.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/ExportImportMemberSearchService.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/BackgroundJobs/ImportContactJob.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/BackgroundJobs/ImportContactsJob.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
Description: 
It works for cases for import inside root, inside organization, and by Organization Id (Outer Id) from file.
However, by OrgId it is other US. 
Do not check cases:
*  With duplicates validation. Will be delivered separately. 
*  dynamic properties. Will be delivered separately. 
*  with the creating of new contacts organization. OtherUS.
*  with accounts creating/updating. Other US.
--
QA-test: VDS-1302
Demo-test: VDS-1304
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-27-7ebed688.zip
> VDS-1837 Implement contacts creating at the contacts import

- src/VirtoCommerce.CustomerExportImportModule.Web/Content/css/customer-export-import.css
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.tpl.html
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-28-46d19efb.zip
> VDS-1731: Add selector for the import type on file upload

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExtendedMembersSearchCriteria.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedCustomerDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/ExportImportMemberSearchService.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntitiesAreNotDuplicatesValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
Description: 
--
QA-test: VDS-1323
Demo-test: VDS-1324
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-31-de7eb6b5.zip
> VDS-1321 Implement contacts updating logic

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/IExportWriterFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/ExportImport/GenericClassMap.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedCustomerDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerDataExporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerImportPagedDataSourceFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/ExportWriter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/ExportWriterFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportDynamicPropertiesValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportDynamicPropertyValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntitiesAreNotDuplicatesValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportMemberValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerImportPagedDataSourceTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/TestHelper.cs
Description: 
--
QA-test: 
Demo-test: 
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-29-a79a1820.zip
> VDS-1838, VDS-1854, VDS-1855: Add validation & fix dynamic properties save

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportPushNotification.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerImportReporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ImportPushNotificationExtensions.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ValidationExtensions.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportReporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedCustomerDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntitiesAreNotDuplicatesValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntityIsNotDuplicateValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportMemberValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
- src/VirtoCommerce.CustomerExportImportModule.Web/Content/css/customer-export-import.css
- src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/dialogs/customerImport-dialog.tpl.html
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/resources/import.js
- src/VirtoCommerce.CustomerExportImportModule.Web/module.manifest
Description: 
--
QA-test: VDS-1361
Demo-test: VDS-1362
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-30-ca2a4e43.zip
> VDS-1360: Development import statistics for UI

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
Description: 
--
QA-test: 
Demo-test: VDS-1302
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-32-1f936846.zip
> VDS-1299: Fix empty fields splitting

- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-33-81ede918.zip
> VDS-1931: Remove sameFileUpload filter

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataPreview.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataPreviewRequest.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataValidationRequest.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerDataValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICustomerImportPagedDataSource.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICustomerImportPagedDataSourceFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerDataValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportHelper.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedCustomerDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerImportPagedDataSource.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerImportPagedDataSourceFactory.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.tpl.html
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.tpl.html
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerImportPagedDataSourceTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/TestHelper.cs
Description: 
--
QA-test: VDS-1596
Demo-test: VDS-1598
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-34-1de9f309.zip
> VDS-1593 Implement backend for organizations import preview

- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.tpl.html
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/dialogs/customerDeleteAndClose-dialog.tpl.html
Description: 
--
QA-test: VDS-1929
Demo-test: VDS-1930
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-35-fcc606ca.zip
> VDS-1883: Implement closing preview blade if new file upload

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportProgressInfo.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportPushNotification.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ExportPushNotificationExtensions.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerDataExporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/export-processing.tpl.html
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-36-921d991d.zip
> VDS-1919: Hide links to empty files

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/EmailValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportMemberValidator.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-41-071396a9.zip
> VDS-2022: Add 'Emails' column to import/export

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableOrganization.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-43-908b5305.zip
> VDS-1997: Exclude userGroups from contacts and organizations

- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
Description: 
--
QA-test: VDS-1309
Demo-test: VDS-1311
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-44-b100a730.zip
> VDS-2060: Add validation and error messages for account

- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
Description: 
--
QA-test: 
Demo-test: 
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-45-79a5b929.zip
> VDS-2059: Duplicated accounts

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
Description: 
--
QA-test: VDS-1309
Demo-test: VDS-1311
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-46-8c649a21.zip
> VDS-2058 Implement the accounts creating logic at the contacts import

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/FakeSignInManager.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/FakeUserManager.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/VirtoCommerce.CustomerExportImportModule.Tests.csproj
Description: 
--
QA-test: VDS-1531
Demo-test: VDS-1533
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-47-86863353.zip
> VDS-2062: Password set & validate

- src/VirtoCommerce.CustomerExportImportModule.Core/Services/IPasswordGenerator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CryptoRandom.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/PasswordGenerator.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
Description: 
--
QA-test: VDS-1531
Demo-test: VDS-1533
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-48-0602658d.zip
> VDS-2063: Generate password

- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
Description: 
Here are two combined tasks in one: 
Development:  VDS-1544, VDS-1537
QA: VDS-1546, VDS-1538
Demo: VDS-1547, VDS-1540
--
QA-test: VDS-1546
Demo-test: VDS-1547
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-51-26df89dd.zip
> VDS-1544, VDS-1537: Add permissions for customers Export and Import

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAddressValidator.cs
Description: 
--
QA-test: VDS-1907
Demo-test: VDS-1908
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-49-6fa09d49.zip
> VDS-2248, VDS-1906: Safe parse & add address type default value

- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedDataImporter.cs
Description: 
--
QA-test: VDS-2254
Demo-test: VDS-2255
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-50-c0a0c120.zip
> VDS-2297: Fix rows order in error report

- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
And fix typo in the localization
Description:
Was
"Password doesn’t meet the platform security policy. Please, contact administrator"
Now
"Password does not meet the platform security policy. Please, contact administrator"
QA-test: VDS-2357
Demo-test: VDS-2358
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-52-cb0ec8c3.zip
> VDS-2256  Replace doesn't with doesn not in Password validation error message

- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/export-processing.tpl.html
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
Description: 
--
QA-test: VDS-2254
Demo-test:  VDS-2255
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-53-ef38e935.zip
> VDS-2252 Show exceptions details at import

- docs/Index.md
Description: 
--
QA-test: 
Demo-test: 
Download artifact URL:
> Update Index.md (#59)

- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerExportPagedDataSource.cs
Description: 
--
QA-test: VDS-2882
Demo-test: VDS-2883
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-62-2b22bcc1.zip
> VDS-2884: Fix null in arrays of IDs

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportProgressInfo.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportPushNotification.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/VirtoCommerce.CustomerExportImportModule.Core.csproj
- src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ImportPushNotificationExtensions.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedOrganizationDataImporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAddressValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
Description: 
--
QA-test: VDS-2751
Demo-test: VDS-2752
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-63-11172eaa.zip
> VDS-2748 VDS-2662 Convert ISO2 to ISO3. Change the required adresse's columns set for the import

- src/VirtoCommerce.CustomerExportImportModule.Data/Services/ExportImportMemberSearchService.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
Description: 
--
QA-test: 
Demo-test: 
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_1.0.0-pr-65-bfbd057a.zip
> VDS-3020: Do not erase keyword

- src/VirtoCommerce.CustomerExportImportModule.Web/package-lock.json
- src/VirtoCommerce.CustomerExportImportModule.Web/package.json
- src/VirtoCommerce.CustomerExportImportModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
> PT-9395: add nodejs-lts support

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableOrganization.cs
- src/VirtoCommerce.CustomerExportImportModule.Core/VirtoCommerce.CustomerExportImportModule.Core.csproj
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAddressValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportMemberValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
- src/VirtoCommerce.CustomerExportImportModule.Web/module.manifest
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
- Add export/import address region code
- Add validation address region code
> Add export/import address region code

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/VirtoCommerce.CustomerExportImportModule.Tests.csproj
- Set the IsDefault property for the imported address, if there is no other default address with the same type
- Check CountryCode and RegionId of existed address
> Set IsDefault property for imported address

- Directory.Build.props
- src/VirtoCommerce.CustomerExportImportModule.Core/VirtoCommerce.CustomerExportImportModule.Core.csproj
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerDataValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerExportPagedDataSource.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
- src/VirtoCommerce.CustomerExportImportModule.Web/module.manifest
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerExportPagedDataSourceTests.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/VirtoCommerce.CustomerExportImportModule.Tests.csproj
- Change all dependency module version to 3.400
- Code refactoring
> Upgrade platfrom to 3.400

- Directory.Build.props
- src/VirtoCommerce.CustomerExportImportModule.Core/VirtoCommerce.CustomerExportImportModule.Core.csproj
- src/VirtoCommerce.CustomerExportImportModule.Data/Repositories/VirtoCommerceCustomerExportImportDbContext.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerImportPagedDataSource.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
- src/VirtoCommerce.CustomerExportImportModule.Web/VirtoCommerce.CustomerExportImportModule.Web.csproj
- src/VirtoCommerce.CustomerExportImportModule.Web/module.manifest
- src/VirtoCommerce.CustomerExportImportModule.Web/package-lock.json
- tests/VirtoCommerce.CustomerExportImportModule.Tests/VirtoCommerce.CustomerExportImportModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_3.800.0-pr-86-bb3c.zip
> PT-14740: .net 8

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/IImportAddressValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/IImportMemberValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAddressValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportMemberValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportOrganizationsValidator.cs
- src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
- Add validator interfaces IImportMemberValidator<T> and IImportAddressValidator<T>
- Register validators in DI container to enable extensibility
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_3.802.0-pr-89-7eb8.zip
> feat: Add validator interfaces and register to DI

- src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
- tests/VirtoCommerce.CustomerExportImportModule.Tests/VirtoCommerce.CustomerExportImportModule.Tests.csproj
Validate AccountLogin with AllowedUserNameCharacters when import contacts
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_3.804.0-pr-92-4c6f.zip
> feat: Validate AccountLogin with AllowedUserNameCharacters

- src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
- Create user with AbstractTypeFactory
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_3.807.0-pr-95-1068.zip
> fix: Create user with AbstractTypeFactory

- src/VirtoCommerce.CustomerExportImportModule.Core/VirtoCommerce.CustomerExportImportModule.Core.csproj
- src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportReporter.cs
- src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
- src/VirtoCommerce.CustomerExportImportModule.Web/module.manifest
- tests/VirtoCommerce.CustomerExportImportModule.Tests/VirtoCommerce.CustomerExportImportModule.Tests.csproj
- Update dependencies
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_3.808.0-pr-97-1245.zip
> feat: Update dependencies

- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/de.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/es.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/fr.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/it.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/ja.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/pl.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/pt.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/ru.VirtoCommerce.CustomerExportImport.json
- src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/zh.VirtoCommerce.CustomerExportImport.json
10 localization files
https://virtocommerce.atlassian.net/browse/VCST-2126
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerExportImport_3.809.0-pr-99-7549.zip
> 10 localization files
